---
# tasks/main.yml

- name: Ensure certificate chain file presents
  copy:
    src: "{{ apache_certificates_dir }}/{{ item.certificate_chain_file | basename }}"
    dest: "{{ item.certificate_chain_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ apache_vhosts_ssl }}"
  when: apache_create_vhosts and not((apache_certificates_dir is undefined) or (apache_certificates_dir is none) or (apache_certificates_dir | trim == ''))

- name: Ensure certificate file presents
  copy:
    src: "{{ apache_certificates_dir }}/{{ item.certificate_file | basename }}"
    dest: "{{ item.certificate_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ apache_vhosts_ssl }}"
  when: apache_create_vhosts and not((apache_certificates_dir is undefined) or (apache_certificates_dir is none) or (apache_certificates_dir | trim == ''))

- name: Ensure certificate key file presents
  copy:
    src: "{{ apache_certificates_dir }}/{{ item.certificate_key_file | basename }}"
    dest: "{{ item.certificate_key_file }}"
    owner: "root"
    group: "root"
    mode: "0600"
  with_items: "{{ apache_vhosts_ssl }}"
  when: apache_create_vhosts and not((apache_certificates_dir is undefined) or (apache_certificates_dir is none) or (apache_certificates_dir | trim == ''))
